version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - flask_app

  flask_app:
    build: .
    ports:
    - target: 5000
      protocol: tcp
